/**
 * Cat.js — the deformable cat.
 *
 * The cat is a spine: a chain of nodes running nose → rump, each carrying a
 * body radius. The silhouette you see is generated by offsetting that spine
 * outward by its radius (see view/CatView.js), so any change to the spine
 * immediately reshapes the whole animal.
 *
 * The spine is simulated with Verlet integration plus position-based
 * constraints, solved in this order every substep:
 *
 *   1. integrate  — gravity moves nodes down
 *   2. shape      — the spine is pulled back toward its relaxed curve
 *   3. stretch    — segments keep their rest length (the spine is not elastic)
 *   4. contact    — the belly is pushed up out of the bed
 *
 * Steps 2 and 3 repeat `PHYSICS.iterations` times, which is what makes a
 * stiff-but-not-rigid spine possible without a real solver. Step 4 runs once,
 * and only partially — see PHYSICS.contactStiffnessSoft in config.js for why
 * that separation matters. The leftover penetration at each node is its
 * `load`: the pressure map and the comfort score both read it.
 */

import { CAT, PHYSICS, FLOOR_Y, BED } from '../config.js';
import { getCatDesign, DEFAULT_CAT_ID } from '../cats/index.js';
import { sampleProfile, signedAngle, lerp } from '../core/math2d.js';

export class Cat {
  /**
   * @param {string} [designId] Which cat to be — see src/cats/index.js.
   * @param {string} [sizeKey] One of CAT.sizes.
   */
  constructor(designId = DEFAULT_CAT_ID, sizeKey = 'medium') {
    this.sizeKey = sizeKey;
    this.setDesign(designId);
  }

  /** Scale factor for the current size preset. */
  get scale() {
    return (CAT.sizes[this.sizeKey] ?? CAT.sizes.medium).scale;
  }

  /** Id of the cat currently being simulated. */
  get designId() {
    return this.design.id;
  }

  /** Becomes a different cat, keeping the current size. */
  setDesign(designId) {
    this.design = getCatDesign(designId);
    this._build();
  }

  /**
   * World units per SVG unit of this cat's artwork, at the current size. The
   * view needs it to place the drawing; the model needs it to turn the measured
   * belly into a collision radius.
   */
  get worldPerArtUnit() {
    const art = this.design.artData;
    if (!art) return 1;
    return (this.design.body.length * this.scale) / (art.bodyX1 - art.bodyX0);
  }

  /** Keeps the current cat, changes how big it is. */
  setSize(sizeKey) {
    this.sizeKey = sizeKey;
    this._build();
  }

  /**
   * (Re)builds every node array from the current design and size. Called
   * whenever either of those changes; there is no incremental path on purpose,
   * since rebuilding is cheap and always correct.
   */
  _build() {
    const body = this.design.body;
    const scale = this.scale;
    const count = CAT.nodeCount;

    this.segmentLength = (body.length * scale) / (count - 1);

    /**
     * @type {{x:number,y:number,px:number,py:number,r:number,t:number,
     *         load:number,smoothLoad:number,contact:boolean}[]}
     */
    this.spine = [];
    /** Rest turn angle at each interior joint, radians. Index matches node. */
    this.restTurn = new Array(count).fill(0);

    // The collision radius is measured off the artwork, so the underside the
    // simulation rests on and the underside you see are the same line. It is
    // only a fallback profile before the art has loaded.
    const art = this.design.artData;
    const perUnit = this.worldPerArtUnit;

    for (let i = 0; i < count; i++) {
      const t = i / (count - 1);
      this.spine.push({
        x: 0, y: 0, px: 0, py: 0,
        r: art ? art.bellyAt(t) * perUnit : 80 * scale,
        t,
        load: 0,
        smoothLoad: 0,
        contact: false,
      });
      this.restTurn[i] = sampleProfile(body.restCurve, t);
    }

    // Angle the rest curve happens to end up at when walked from heading 0.
    // Subtracting it lets restTilt mean "chord angle" rather than "initial
    // heading", so editing the curvature profile cannot tip the cat over.
    this.restChordAngle = measureChordAngle(this._walk(0, 0, 0));

    this._buildShapeClusters();
    this.reset();
  }

  /**
   * Precomputes everything the shape-matching solver needs: the rest pose in
   * local coordinates, the overlapping windows that cover the spine, and the
   * scratch buffers the solver accumulates into (allocated once so the physics
   * loop stays allocation-free).
   */
  _buildShapeClusters() {
    const count = this.spine.length;

    /** Rest pose as plain points. Only its relative geometry is used. */
    this.restLocal = this._walk(0, 0, 0).map((p) => ({ x: p.x, y: p.y }));

    this.clusters = [];
    const size = Math.min(PHYSICS.clusterSize, count);
    for (let start = 0; start + size <= count; start += PHYSICS.clusterStride) {
      this.clusters.push(start);
    }
    // Guarantee the final nodes are covered even if the stride skips past them.
    const lastStart = count - size;
    if (this.clusters[this.clusters.length - 1] !== lastStart) {
      this.clusters.push(lastStart);
    }
    this.clusterSize = size;

    this._targetX = new Float64Array(count);
    this._targetY = new Float64Array(count);
    this._targetWeight = new Float64Array(count);
  }

  /**
   * Horizontal position the nose starts at: chosen so the body is centred on
   * the bed at every size preset.
   */
  get defaultNoseX() {
    return (BED.left + BED.right) / 2 - (this.segmentLength * (this.spine.length - 1)) / 2;
  }

  /** Drops the cat back onto the bed from its spawn height, in rest pose. */
  reset() {
    const rest = this.restShape({ noseY: CAT.spawnY });
    this.spine.forEach((node, i) => {
      node.x = node.px = rest[i].x;
      node.y = node.py = rest[i].y;
      node.load = node.smoothLoad = 0;
      node.contact = false;
    });

    /** Where the body's centre of mass wants to stay, horizontally. */
    this.anchorCenterX = averageX(rest);
  }

  /**
   * The pose the cat would take with no bed at all: its spine integrated from
   * the rest curvature profile. This is the reference shape for both the
   * posture score and Auto-fit.
   *
   * @param {{noseX?:number, noseY?:number, tilt?:number}} [options]
   * @returns {{x:number,y:number,r:number}[]}
   */
  restShape({ noseX = this.defaultNoseX, noseY = 0, tilt = this.design.body.restTilt } = {}) {
    return this._walk(noseX, noseY, tilt - this.restChordAngle);
  }

  /**
   * Integrates the rest curvature into positions, starting at (x, y) with the
   * given initial heading. Kept separate from `restShape` so that measuring
   * the chord angle and producing the final pose use identical maths.
   */
  _walk(noseX, noseY, heading) {
    const L = this.segmentLength;
    const out = [];
    let x = noseX;
    let y = noseY;
    let dir = heading;

    for (let i = 0; i < this.spine.length; i++) {
      out.push({ x, y, r: this.spine[i].r });
      if (i > 0) dir += this.restTurn[i];
      x += Math.cos(dir) * L;
      y += Math.sin(dir) * L;
    }
    return out;
  }

  /**
   * Advances the simulation by one rendered frame.
   * @param {import('./Bed.js').Bed} bed
   */
  update(bed) {
    const dt = PHYSICS.timeStep;
    const gravityStep = PHYSICS.gravity * dt * dt;

    for (let step = 0; step < PHYSICS.substeps; step++) {
      this._integrate(this.spine, gravityStep);

      // Structural constraints, solved to near-convergence.
      for (let iter = 0; iter < PHYSICS.iterations; iter++) {
        this._solveShape();
        this._solveStretch();
      }

      // Contact, applied once and compliantly.
      this._solveContact(bed);
    }

    this._recenter();
    this._smoothLoads();
  }

  /** Verlet step: position += velocity * damping + gravity. */
  _integrate(nodes, gravityStep) {
    for (const node of nodes) {
      const vx = (node.x - node.px) * PHYSICS.damping;
      const vy = (node.y - node.py) * PHYSICS.damping;
      node.px = node.x;
      node.py = node.y;
      node.x += vx;
      node.y += vy + gravityStep;
    }
  }

  /** Keeps adjacent spine nodes exactly one segment length apart. */
  _solveStretch() {
    const L = this.segmentLength;
    const k = PHYSICS.stretchStiffness;

    for (let i = 0; i < this.spine.length - 1; i++) {
      const a = this.spine[i];
      const b = this.spine[i + 1];
      const dx = b.x - a.x;
      const dy = b.y - a.y;
      const dist = Math.hypot(dx, dy) || 1e-6;
      const correction = ((dist - L) / dist) * 0.5 * k;
      const cx = dx * correction;
      const cy = dy * correction;
      a.x += cx;
      a.y += cy;
      b.x -= cx;
      b.y -= cy;
    }
  }

  /**
   * Shape matching: the cat's resistance to bending.
   *
   * For each overlapping window of the spine, the rest pose of that window is
   * rigidly fitted (rotation + translation, no scaling) onto where those nodes
   * currently are. The fit says "given roughly where this stretch of cat is and
   * which way it is facing, here is where its nodes would be if it were
   * relaxed". Each node averages the fits of every window covering it and moves
   * a fraction of the way toward that average.
   *
   * Because each window is solved globally rather than joint by joint, a
   * disturbance anywhere is answered immediately along the whole window, which
   * is what makes this stable where per-joint constraints were not.
   */
  _solveShape() {
    const spine = this.spine;
    const size = this.clusterSize;
    const tx = this._targetX;
    const ty = this._targetY;
    const weight = this._targetWeight;

    tx.fill(0);
    ty.fill(0);
    weight.fill(0);

    for (let c = 0; c < this.clusters.length; c++) {
      const start = this.clusters[c];

      // Centroids of the rest window and the current window.
      let restCx = 0; let restCy = 0; let curCx = 0; let curCy = 0;
      for (let j = 0; j < size; j++) {
        const rest = this.restLocal[start + j];
        const node = spine[start + j];
        restCx += rest.x; restCy += rest.y;
        curCx += node.x; curCy += node.y;
      }
      restCx /= size; restCy /= size; curCx /= size; curCy /= size;

      // Best-fit rotation between the two centred point sets. For 2D this has
      // a closed form: the angle of the summed cross/dot products.
      let dot = 0; let cross = 0;
      for (let j = 0; j < size; j++) {
        const rx = this.restLocal[start + j].x - restCx;
        const ry = this.restLocal[start + j].y - restCy;
        const cx = spine[start + j].x - curCx;
        const cy = spine[start + j].y - curCy;
        dot += rx * cx + ry * cy;
        cross += rx * cy - ry * cx;
      }
      const angle = Math.atan2(cross, dot);
      const cos = Math.cos(angle);
      const sin = Math.sin(angle);

      // Accumulate this window's opinion of where each of its nodes belongs.
      for (let j = 0; j < size; j++) {
        const rx = this.restLocal[start + j].x - restCx;
        const ry = this.restLocal[start + j].y - restCy;
        const index = start + j;
        tx[index] += curCx + rx * cos - ry * sin;
        ty[index] += curCy + rx * sin + ry * cos;
        weight[index] += 1;
      }
    }

    const k = PHYSICS.shapeStiffness;
    for (let i = 0; i < spine.length; i++) {
      if (weight[i] === 0) continue;
      const node = spine[i];
      node.x += (tx[i] / weight[i] - node.x) * k;
      node.y += (ty[i] / weight[i] - node.y) * k;
    }
  }

  /**
   * Pushes the belly up out of the bed. Contact is resolved vertically only,
   * which keeps the cat from creeping sideways on a sloped surface and makes
   * the pressure readings easy to interpret.
   *
   * The push is partial, so a node that is bearing weight settles a little way
   * into the cushion and stays there. That residual penetration is recorded as
   * the node's load: a heavily loaded spot sinks further, exactly as foam does.
   */
  _solveContact(bed) {
    const stiffness = lerp(
      PHYSICS.contactStiffnessSoft,
      PHYSICS.contactStiffnessFirm,
      bed.firmness,
    );

    for (const node of this.spine) {
      const surface = bed.surfaceAt(node.x) ?? FLOOR_Y;
      const penetration = node.y + node.r - surface;

      if (penetration > 0) {
        node.y -= penetration * stiffness;
        node.load = penetration;
        node.contact = true;
      } else {
        node.load = 0;
        node.contact = false;
      }

      // Safety net so a cat that misses the bed entirely does not fall forever.
      const floorBelly = node.y + node.r;
      if (floorBelly > FLOOR_Y) node.y -= floorBelly - FLOOR_Y;
    }
  }

  /**
   * Constraint solving nudges nodes horizontally, which over thousands of
   * frames would let the cat wander off the bed. This slides the whole body
   * back toward its intended horizontal position without altering its shape.
   */
  _recenter() {
    const drift = this.anchorCenterX - averageX(this.spine);
    if (Math.abs(drift) < 0.01) return;

    const shift = drift * 0.12;
    for (const node of this.spine) {
      node.x += shift;
      node.px += shift;
    }
  }

  /** Low-pass filters contact load so the pressure display does not flicker. */
  _smoothLoads() {
    for (const node of this.spine) {
      node.smoothLoad = lerp(node.smoothLoad, node.load, PHYSICS.loadSmoothing);
    }
  }

  /** Largest smoothed load across the body, for normalising the pressure map. */
  get peakLoad() {
    let peak = 0;
    for (const node of this.spine) peak = Math.max(peak, node.smoothLoad);
    return peak;
  }

  /** Actual turn angle at each interior joint, for comparison with restTurn. */
  measureTurns() {
    const turns = new Array(this.spine.length).fill(0);
    for (let i = 1; i < this.spine.length - 1; i++) {
      const a = this.spine[i - 1];
      const b = this.spine[i];
      const c = this.spine[i + 1];
      turns[i] = signedAngle(b.x - a.x, b.y - a.y, c.x - b.x, c.y - b.y);
    }
    return turns;
  }

}

/** Angle of the straight line from the first point to the last. */
function measureChordAngle(points) {
  const first = points[0];
  const last = points[points.length - 1];
  return Math.atan2(last.y - first.y, last.x - first.x);
}

function averageX(nodes) {
  let sum = 0;
  for (const node of nodes) sum += node.x;
  return sum / nodes.length;
}
